server.servlet.context-path=/ch9
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/final_ch9?characterEncoding=utf8

spring.datasource.username=root

spring.datasource.password=123456

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis-Plus配置
mybatis-plus.type-aliases-package=com.ch.ch9.entity
mybatis-plus.mapper-locations=classpath:mappers/**/*.xml
mybatis-plus.configuration.map-underscore-to-camel-case=false

#MyBatis-Plus全局配置
mybatis-plus.global-config.db-config.id-type=auto

logging.level.com.ch.ch9.repository=debug
logging.level.org.apache.ibatis=debug
logging.level.java.sql=debug
logging.level.com.zaxxer.hikari.pool=debug

spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.strategy.content.enabled=true
spring.web.resources.chain.strategy.content.paths=/**

server.error.include-stacktrace=always
server.error.include-message=always
server.error.include-exception=true

spring.servlet.multipart.max-file-size=50MB

spring.servlet.multipart.max-request-size=500MB







